test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local_minio:
  service: S3
  endpoint: <%= ENV.fetch('MINIO_ENDPOINT', 'http://localhost:9000') %>
  access_key_id: <%= ENV.fetch('MINIO_ACCESS_KEY', 'minioadmin') %>
  secret_access_key: <%= ENV.fetch('MINIO_SECRET_KEY', 'minioadmin') %>
  region: us-east-1
  bucket: <%= ENV.fetch('MINIO_BUCKET', 'coffee-parches') %>
  force_path_style: true

amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_BUCKET'] %>
