source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1"
gem "jwt"
gem "pundit"
gem "rack-cors"
gem "rswag-api"
gem "rswag-ui"
gem "rswag-specs"
gem "bootsnap", require: false
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"
gem "image_processing", "~> 1.2"
gem "aws-sdk-s3", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end
